import type { MatchDetail } from "./types";

// ─── Shared references ──────────────────────────────────────────────

const PREMIER_LEAGUE = { id: 1, name: "Premier League", slug: "premier-league-1", country: "England", logo_url: "" };
const LA_LIGA = { id: 2, name: "La Liga", slug: "la-liga-2", country: "Spain", logo_url: "" };
const CHAMPIONS_LEAGUE = { id: 3, name: "Champions League", slug: "champions-league-3", country: "Europe", logo_url: "" };

const ARSENAL = { id: 10, name: "Arsenal", slug: "arsenal-10", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png" };
const CHELSEA = { id: 13, name: "Chelsea", slug: "chelsea-13", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/pbf4ul1782638263.png" };
const LIVERPOOL = { id: 11, name: "Liverpool", slug: "liverpool-11", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png" };
const MAN_CITY = { id: 12, name: "Man City", slug: "man-city-12", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png" };
const REAL_MADRID = { id: 20, name: "Real Madrid", slug: "real-madrid-20", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/vwvwrw1473502969.png" };
const BARCELONA = { id: 21, name: "Barcelona", slug: "barcelona-21", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/wq9sir1639406443.png" };
const BAYERN = { id: 30, name: "Bayern Munich", slug: "bayern-munich-30", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/01ogkh1716960412.png" };
const DORTMUND = { id: 31, name: "Dortmund", slug: "dortmund-31", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/tqo8ge1716960353.png" };
const INTER = { id: 40, name: "Inter Milan", slug: "inter-milan-40", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/ryhu6d1617113103.png" };
const AC_MILAN = { id: 41, name: "AC Milan", slug: "ac-milan-41", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/wvspur1448806617.png" };
const JUVENTUS = { id: 42, name: "Juventus", slug: "juventus-42", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/uxf0gr1742983727.png" };
const NAPOLI = { id: 43, name: "Napoli", slug: "napoli-43", crest_url: "https://r2.thesportsdb.com/images/media/team/badge/l8qyxv1742982541.png" };

// ─── Mock Match Details ─────────────────────────────────────────────

export const MOCK_MATCH_DETAILS: Record<number, MatchDetail> = {
  // ── Arsenal vs Chelsea (LIVE 67') ────────────────────────────────
  101: {
    id: 101,
    slug: "arsenal-vs-chelsea-101",
    status: "live",
    minute: 67,
    date: "2026-08-22",
    kickoff_time: "15:00",
    venue: "Emirates Stadium",
    league: PREMIER_LEAGUE,
    home_team: ARSENAL,
    away_team: CHELSEA,
    home_score: 2,
    away_score: 1,
    attendance: 60260,
    referee: "Michael Oliver",
    home_lineup: [
      { player: { id: 101, name: "D. Raya", slug: "david-raya-101", position: "Goalkeeper", number: 22, nationality: "Spain" }, position: "GK", shirt_number: 22, rating: 7.2 },
      { player: { id: 102, name: "B. White", slug: "ben-white-102", position: "Defender", number: 4, nationality: "England" }, position: "RB", shirt_number: 4, rating: 7.0 },
      { player: { id: 103, name: "W. Saliba", slug: "william-saliba-103", position: "Defender", number: 2, nationality: "France" }, position: "CB", shirt_number: 2, rating: 7.5 },
      { player: { id: 104, name: "G. Gabriel", slug: "gabriel-magalhaes-104", position: "Defender", number: 6, nationality: "Brazil" }, position: "CB", shirt_number: 6, rating: 7.3 },
      { player: { id: 105, name: "J. Timber", slug: "jurrien-timber-105", position: "Defender", number: 12, nationality: "Netherlands" }, position: "LB", shirt_number: 12, rating: 7.1 },
      { player: { id: 106, name: "D. Rice", slug: "declan-rice-106", position: "Midfielder", number: 41, nationality: "England" }, position: "CDM", shirt_number: 41, rating: 7.8 },
      { player: { id: 107, name: "M. Odegaard", slug: "martin-odegaard-107", position: "Midfielder", number: 8, nationality: "Norway" }, position: "CAM", shirt_number: 8, rating: 8.2 },
      { player: { id: 108, name: "K. Havertz", slug: "kai-havertz-108", position: "Midfielder", number: 29, nationality: "Germany" }, position: "CM", shirt_number: 29, rating: 7.0 },
      { player: { id: 109, name: "B. Saka", slug: "bukayo-saka-109", position: "Forward", number: 7, nationality: "England" }, position: "RW", shirt_number: 7, rating: 8.5 },
      { player: { id: 110, name: "G. Martinelli", slug: "gabriel-martinelli-110", position: "Forward", number: 11, nationality: "Brazil" }, position: "LW", shirt_number: 11, rating: 7.4 },
      { player: { id: 111, name: "K. Havertz", slug: "kai-havertz-striker-111", position: "Forward", number: 29, nationality: "Germany" }, position: "ST", shirt_number: 29, rating: 7.6 },
    ],
    away_lineup: [
      { player: { id: 131, name: "R. Sanchez", slug: "roberto-sanchez-131", position: "Goalkeeper", number: 1, nationality: "Spain" }, position: "GK", shirt_number: 1, rating: 6.5 },
      { player: { id: 132, name: "M. Gusto", slug: "malo-gusto-132", position: "Defender", number: 27, nationality: "France" }, position: "RB", shirt_number: 27, rating: 6.8 },
      { player: { id: 133, name: "W. Fofana", slug: " Wesley-fofana-133", position: "Defender", number: 33, nationality: "France" }, position: "CB", shirt_number: 33, rating: 6.7 },
      { player: { id: 134, name: "L. Colwill", slug: "levi-colwill-134", position: "Defender", number: 26, nationality: "England" }, position: "CB", shirt_number: 26, rating: 6.9 },
      { player: { id: 135, name: "M. Cucurella", slug: "marc-cucurella-135", position: "Defender", number: 3, nationality: "Spain" }, position: "LB", shirt_number: 3, rating: 6.6 },
      { player: { id: 136, name: "N. Kante", slug: "ngolo-kante-136", position: "Midfielder", number: 7, nationality: "France" }, position: "CDM", shirt_number: 7, rating: 7.1 },
      { player: { id: 137, name: "M. Caicedo", slug: "moises-caicedo-137", position: "Midfielder", number: 25, nationality: "Ecuador" }, position: "CM", shirt_number: 25, rating: 7.0 },
      { player: { id: 138, name: "C. Palmer", slug: "cole-palmer-138", position: "Midfielder", number: 20, nationality: "England" }, position: "CAM", shirt_number: 20, rating: 7.3 },
      { player: { id: 139, name: "N. Madueke", slug: "noni-madueke-139", position: "Forward", number: 11, nationality: "England" }, position: "RW", shirt_number: 11, rating: 6.8 },
      { player: { id: 140, name: "P. Neto", slug: "pedro-neto-140", position: "Forward", number: 7, nationality: "Portugal" }, position: "LW", shirt_number: 7, rating: 6.9 },
      { player: { id: 141, name: "N. Jackson", slug: "nicolas-jackson-141", position: "Forward", number: 15, nationality: "Senegal" }, position: "ST", shirt_number: 15, rating: 6.7 },
    ],
    events: [
      { id: 1, minute: 23, added_time: null, type: "goal", team: ARSENAL, player: { id: 109, name: "B. Saka", slug: "bukayo-saka-109", position: "Forward", number: 7, nationality: "England" }, second_player: { id: 107, name: "M. Odegaard", slug: "martin-odegaard-107", position: "Midfielder", number: 8, nationality: "Norway" }, detail: "Right-footed shot" },
      { id: 2, minute: 35, added_time: null, type: "goal", team: CHELSEA, player: { id: 138, name: "C. Palmer", slug: "cole-palmer-138", position: "Midfielder", number: 20, nationality: "England" }, second_player: null, detail: "Penalty" },
      { id: 3, minute: 42, added_time: 1, type: "yellow_card", team: CHELSEA, player: { id: 136, name: "N. Kante", slug: "ngolo-kante-136", position: "Midfielder", number: 7, nationality: "France" }, second_player: null, detail: "Tactical foul" },
      { id: 4, minute: 55, added_time: null, type: "goal", team: ARSENAL, player: { id: 110, name: "G. Martinelli", slug: "gabriel-martinelli-110", position: "Forward", number: 11, nationality: "Brazil" }, second_player: { id: 109, name: "B. Saka", slug: "bukayo-saka-109", position: "Forward", number: 7, nationality: "England" }, detail: "Left-footed shot" },
      { id: 5, minute: 62, added_time: null, type: "substitution", team: CHELSEA, player: { id: 142, name: "R. Lavia", slug: "roméo-lavia-142", position: "Midfielder", number: 45, nationality: "Belgium" }, second_player: { id: 136, name: "N. Kante", slug: "ngolo-kante-136", position: "Midfielder", number: 7, nationality: "France" }, detail: null },
    ],
    stats: {
      possession: [58, 42],
      shots: [14, 9],
      shots_on_target: [6, 3],
      corners: [7, 4],
      fouls: [8, 12],
      yellow_cards: [1, 2],
      red_cards: [0, 0],
    },
  },

  // ── Real Madrid vs Barcelona (LIVE 34') ──────────────────────────
  102: {
    id: 102,
    slug: "real-madrid-vs-barcelona-102",
    status: "live",
    minute: 34,
    date: "2026-08-22",
    kickoff_time: "21:00",
    venue: "Santiago Bernabeu",
    league: LA_LIGA,
    home_team: REAL_MADRID,
    away_team: BARCELONA,
    home_score: 1,
    away_score: 1,
    attendance: 81044,
    referee: "Juan Martínez Munuera",
    home_lineup: [
      { player: { id: 201, name: "T. Courtois", slug: "thibaut-courtois-201", position: "Goalkeeper", number: 1, nationality: "Belgium" }, position: "GK", shirt_number: 1, rating: 6.8 },
      { player: { id: 202, name: "D. Carvajal", slug: "dani-carvajal-202", position: "Defender", number: 2, nationality: "Spain" }, position: "RB", shirt_number: 2, rating: 7.0 },
      { player: { id: 203, name: "É. Militão", slug: "eder-militao-203", position: "Defender", number: 3, nationality: "Brazil" }, position: "CB", shirt_number: 3, rating: 7.2 },
      { player: { id: 204, name: "A. Rüdiger", slug: "antonio-rudiger-204", position: "Defender", number: 22, nationality: "Germany" }, position: "CB", shirt_number: 22, rating: 7.1 },
      { player: { id: 205, name: "F. Mendy", slug: "ferland-mendy-205", position: "Defender", number: 23, nationality: "France" }, position: "LB", shirt_number: 23, rating: 6.9 },
      { player: { id: 206, name: "T. Kroos", slug: "toni-kroos-206", position: "Midfielder", number: 8, nationality: "Germany" }, position: "CDM", shirt_number: 8, rating: 7.5 },
      { player: { id: 207, name: "L. Modrić", slug: "luka-modric-207", position: "Midfielder", number: 10, nationality: "Croatia" }, position: "CM", shirt_number: 10, rating: 7.8 },
      { player: { id: 208, name: "F. Valverde", slug: "federico-valverde-208", position: "Midfielder", number: 15, nationality: "Uruguay" }, position: "CM", shirt_number: 15, rating: 7.3 },
      { player: { id: 209, name: "V. Jr.", slug: "vinicius-junior-209", position: "Forward", number: 7, nationality: "Brazil" }, position: "LW", shirt_number: 7, rating: 8.4 },
      { player: { id: 210, name: "Rodrygo", slug: "rodrygo-210", position: "Forward", number: 11, nationality: "Brazil" }, position: "RW", shirt_number: 11, rating: 7.2 },
      { player: { id: 211, name: "K. Mbappé", slug: "kylian-mbappe-211", position: "Forward", number: 9, nationality: "France" }, position: "ST", shirt_number: 9, rating: 7.6 },
    ],
    away_lineup: [
      { player: { id: 231, name: "M. ter Stegen", slug: "marc-ter-stegen-231", position: "Goalkeeper", number: 1, nationality: "Germany" }, position: "GK", shirt_number: 1, rating: 7.0 },
      { player: { id: 232, name: "J. Koundé", slug: "jules-kounde-232", position: "Defender", number: 23, nationality: "France" }, position: "RB", shirt_number: 23, rating: 7.1 },
      { player: { id: 233, name: "R. Araújo", slug: "ronald-araujo-233", position: "Defender", number: 4, nationality: "Uruguay" }, position: "CB", shirt_number: 4, rating: 7.3 },
      { player: { id: 234, name: "P. Cubarsí", slug: "pau-cubarsi-234", position: "Defender", number: 2, nationality: "Spain" }, position: "CB", shirt_number: 2, rating: 7.0 },
      { player: { id: 235, name: "A. Balde", slug: "alejandro-balde-235", position: "Defender", number: 3, nationality: "Spain" }, position: "LB", shirt_number: 3, rating: 6.8 },
      { player: { id: 236, name: "Pedri", slug: "pedri-236", position: "Midfielder", number: 8, nationality: "Spain" }, position: "CM", shirt_number: 8, rating: 8.0 },
      { player: { id: 237, name: "Gavi", slug: "gavi-237", position: "Midfielder", number: 6, nationality: "Spain" }, position: "CM", shirt_number: 6, rating: 7.4 },
      { player: { id: 238, name: "F. de Jong", slug: "frenkie-de-jong-238", position: "Midfielder", number: 21, nationality: "Netherlands" }, position: "CDM", shirt_number: 21, rating: 7.2 },
      { player: { id: 239, name: "L. Yamal", slug: "lamine-yamal-239", position: "Forward", number: 19, nationality: "Spain" }, position: "RW", shirt_number: 19, rating: 8.1 },
      { player: { id: 240, name: "Raphinha", slug: "raphinha-240", position: "Forward", number: 11, nationality: "Brazil" }, position: "LW", shirt_number: 11, rating: 7.5 },
      { player: { id: 241, name: "R. Lewandowski", slug: "robert-lewandowski-241", position: "Forward", number: 9, nationality: "Poland" }, position: "ST", shirt_number: 9, rating: 7.3 },
    ],
    events: [
      { id: 10, minute: 12, added_time: null, type: "goal", team: BARCELONA, player: { id: 241, name: "R. Lewandowski", slug: "robert-lewandowski-241", position: "Forward", number: 9, nationality: "Poland" }, second_player: { id: 239, name: "L. Yamal", slug: "lamine-yamal-239", position: "Forward", number: 19, nationality: "Spain" }, detail: "Header" },
      { id: 11, minute: 28, added_time: null, type: "goal", team: REAL_MADRID, player: { id: 209, name: "V. Jr.", slug: "vinicius-junior-209", position: "Forward", number: 7, nationality: "Brazil" }, second_player: { id: 211, name: "K. Mbappé", slug: "kylian-mbappe-211", position: "Forward", number: 9, nationality: "France" }, detail: "Counter-attack" },
      { id: 12, minute: 31, added_time: null, type: "yellow_card", team: REAL_MADRID, player: { id: 204, name: "A. Rüdiger", slug: "antonio-rudiger-204", position: "Defender", number: 22, nationality: "Germany" }, second_player: null, detail: "Foul" },
    ],
    stats: {
      possession: [48, 52],
      shots: [8, 10],
      shots_on_target: [3, 4],
      corners: [3, 5],
      fouls: [6, 5],
      yellow_cards: [1, 0],
      red_cards: [0, 0],
    },
  },

  // ── Liverpool vs Man City (FINISHED 3-2) ─────────────────────────
  103: {
    id: 103,
    slug: "liverpool-vs-man-city-103",
    status: "finished",
    minute: null,
    date: "2026-08-22",
    kickoff_time: "12:30",
    venue: "Anfield",
    league: PREMIER_LEAGUE,
    home_team: LIVERPOOL,
    away_team: MAN_CITY,
    home_score: 3,
    away_score: 2,
    attendance: 53342,
    referee: "Anthony Taylor",
    home_lineup: [
      { player: { id: 301, name: "A. Becker", slug: "alisson-becker-301", position: "Goalkeeper", number: 1, nationality: "Brazil" }, position: "GK", shirt_number: 1, rating: 7.0 },
      { player: { id: 302, name: "T. Alexander-Arnold", slug: "trent-alexander-arnold-302", position: "Defender", number: 66, nationality: "England" }, position: "RB", shirt_number: 66, rating: 8.1 },
      { player: { id: 303, name: "V. van Dijk", slug: "virgil-van-dijk-303", position: "Defender", number: 4, nationality: "Netherlands" }, position: "CB", shirt_number: 4, rating: 8.0 },
      { player: { id: 304, name: "I. Konaté", slug: "ibrahima-konate-304", position: "Defender", number: 5, nationality: "France" }, position: "CB", shirt_number: 5, rating: 7.5 },
      { player: { id: 305, name: "A. Robertson", slug: "andy-robertson-305", position: "Defender", number: 26, nationality: "Scotland" }, position: "LB", shirt_number: 26, rating: 7.3 },
      { player: { id: 306, name: "R. Gravenberch", slug: "ryan-gravenberch-306", position: "Midfielder", number: 38, nationality: "Netherlands" }, position: "CDM", shirt_number: 38, rating: 7.6 },
      { player: { id: 307, name: "S. Mac Allister", slug: "alexis-mac-allister-307", position: "Midfielder", number: 10, nationality: "Argentina" }, position: "CM", shirt_number: 10, rating: 7.8 },
      { player: { id: 308, name: "D. Szoboszlai", slug: "dominik-szoboszlai-308", position: "Midfielder", number: 8, nationality: "Hungary" }, position: "CM", shirt_number: 8, rating: 7.4 },
      { player: { id: 309, name: "M. Salah", slug: "mohamed-salah-309", position: "Forward", number: 11, nationality: "Egypt" }, position: "RW", shirt_number: 11, rating: 9.0 },
      { player: { id: 310, name: "L. Díaz", slug: "luis-diaz-310", position: "Forward", number: 7, nationality: "Colombia" }, position: "LW", shirt_number: 7, rating: 7.9 },
      { player: { id: 311, name: "D. Núñez", slug: "darwin-nunez-311", position: "Forward", number: 9, nationality: "Uruguay" }, position: "ST", shirt_number: 9, rating: 8.2 },
    ],
    away_lineup: [
      { player: { id: 331, name: "E. Ederson", slug: "ederson-331", position: "Goalkeeper", number: 31, nationality: "Brazil" }, position: "GK", shirt_number: 31, rating: 6.2 },
      { player: { id: 332, name: "K. Walker", slug: "kyle-walker-332", position: "Defender", number: 2, nationality: "England" }, position: "RB", shirt_number: 2, rating: 6.5 },
      { player: { id: 333, name: "R. Dias", slug: "ruben-dias-333", position: "Defender", number: 3, nationality: "Portugal" }, position: "CB", shirt_number: 3, rating: 6.8 },
      { player: { id: 334, name: "J. Stones", slug: "john-stones-334", position: "Defender", number: 5, nationality: "England" }, position: "CB", shirt_number: 5, rating: 6.6 },
      { player: { id: 335, name: "J. Gvardiol", slug: "josko-gvardiol-335", position: "Defender", number: 24, nationality: "Croatia" }, position: "LB", shirt_number: 24, rating: 6.7 },
      { player: { id: 336, name: "R. Rodri", slug: "rodri-336", position: "Midfielder", number: 16, nationality: "Spain" }, position: "CDM", shirt_number: 16, rating: 7.5 },
      { player: { id: 337, name: "K. De Bruyne", slug: "kevin-de-bruyne-337", position: "Midfielder", number: 17, nationality: "Belgium" }, position: "CM", shirt_number: 17, rating: 7.8 },
      { player: { id: 338, name: "B. Silva", slug: "bernardo-silva-338", position: "Midfielder", number: 20, nationality: "Portugal" }, position: "CM", shirt_number: 20, rating: 7.4 },
      { player: { id: 339, name: "S. Savinho", slug: "savinho-339", position: "Forward", number: 26, nationality: "Brazil" }, position: "RW", shirt_number: 26, rating: 7.0 },
      { player: { id: 340, name: "J. Grealish", slug: "jack-grealish-340", position: "Forward", number: 10, nationality: "England" }, position: "LW", shirt_number: 10, rating: 6.8 },
      { player: { id: 341, name: "E. Haaland", slug: "erling-haaland-341", position: "Forward", number: 9, nationality: "Norway" }, position: "ST", shirt_number: 9, rating: 7.6 },
    ],
    events: [
      { id: 20, minute: 8, added_time: null, type: "goal", team: MAN_CITY, player: { id: 341, name: "E. Haaland", slug: "erling-haaland-341", position: "Forward", number: 9, nationality: "Norway" }, second_player: { id: 337, name: "K. De Bruyne", slug: "kevin-de-bruyne-337", position: "Midfielder", number: 17, nationality: "Belgium" }, detail: "Low drive" },
      { id: 21, minute: 19, added_time: null, type: "goal", team: LIVERPOOL, player: { id: 309, name: "M. Salah", slug: "mohamed-salah-309", position: "Forward", number: 11, nationality: "Egypt" }, second_player: { id: 302, name: "T. Alexander-Arnold", slug: "trent-alexander-arnold-302", position: "Defender", number: 66, nationality: "England" }, detail: "Right-footed curler" },
      { id: 22, minute: 33, added_time: null, type: "goal", team: LIVERPOOL, player: { id: 311, name: "D. Núñez", slug: "darwin-nunez-311", position: "Forward", number: 9, nationality: "Uruguay" }, second_player: { id: 310, name: "L. Díaz", slug: "luis-diaz-310", position: "Forward", number: 7, nationality: "Colombia" }, detail: "Tap-in" },
      { id: 23, minute: 45, added_time: 2, type: "yellow_card", team: MAN_CITY, player: { id: 334, name: "J. Stones", slug: "john-stones-334", position: "Defender", number: 5, nationality: "England" }, second_player: null, detail: "Foul on Salah" },
      { id: 24, minute: 56, added_time: null, type: "goal", team: MAN_CITY, player: { id: 339, name: "S. Savinho", slug: "savinho-339", position: "Forward", number: 26, nationality: "Brazil" }, second_player: { id: 338, name: "B. Silva", slug: "bernardo-silva-338", position: "Midfielder", number: 20, nationality: "Portugal" }, detail: "Solo run" },
      { id: 25, minute: 71, added_time: null, type: "goal", team: LIVERPOOL, player: { id: 309, name: "M. Salah", slug: "mohamed-salah-309", position: "Forward", number: 11, nationality: "Egypt" }, second_player: null, detail: "Penalty" },
      { id: 26, minute: 78, added_time: null, type: "yellow_card", team: LIVERPOOL, player: { id: 306, name: "R. Gravenberch", slug: "ryan-gravenberch-306", position: "Midfielder", number: 38, nationality: "Netherlands" }, second_player: null, detail: "Professional foul" },
      { id: 27, minute: 90, added_time: 3, type: "fulltime", team: LIVERPOOL, player: { id: 301, name: "A. Becker", slug: "alisson-becker-301", position: "Goalkeeper", number: 1, nationality: "Brazil" }, second_player: null, detail: null },
    ],
    stats: {
      possession: [44, 56],
      shots: [16, 18],
      shots_on_target: [8, 7],
      corners: [6, 8],
      fouls: [10, 9],
      yellow_cards: [1, 1],
      red_cards: [0, 0],
    },
  },

  // ── Bayern Munich vs Dortmund (FINISHED 4-0) ─────────────────────
  104: {
    id: 104,
    slug: "bayern-vs-dortmund-104",
    status: "finished",
    minute: null,
    date: "2026-08-22",
    kickoff_time: "18:30",
    venue: "Allianz Arena",
    league: CHAMPIONS_LEAGUE,
    home_team: BAYERN,
    away_team: DORTMUND,
    home_score: 4,
    away_score: 0,
    attendance: 75000,
    referee: "Danny Makkelie",
    home_lineup: [
      { player: { id: 401, name: "M. Neuer", slug: "manuel-neuer-401", position: "Goalkeeper", number: 1, nationality: "Germany" }, position: "GK", shirt_number: 1, rating: 7.0 },
      { player: { id: 402, name: "J. Kimmich", slug: "joshua-kimmich-402", position: "Defender", number: 6, nationality: "Germany" }, position: "RB", shirt_number: 6, rating: 7.8 },
      { player: { id: 403, name: "M. de Ligt", slug: "mathijs-de-ligt-403", position: "Defender", number: 2, nationality: "Netherlands" }, position: "CB", shirt_number: 2, rating: 7.5 },
      { player: { id: 404, name: "H. Kim", slug: "kim-min-jae-404", position: "Defender", number: 3, nationality: "South Korea" }, position: "CB", shirt_number: 3, rating: 7.6 },
      { player: { id: 405, name: "A. Davies", slug: "alphonso-davies-405", position: "Defender", number: 19, nationality: "Canada" }, position: "LB", shirt_number: 19, rating: 8.0 },
      { player: { id: 406, name: "J. Goretzka", slug: "leon-goretzka-406", position: "Midfielder", number: 8, nationality: "Germany" }, position: "CM", shirt_number: 8, rating: 7.7 },
      { player: { id: 407, name: "K. Coman", slug: "kingsley-coman-407", position: "Midfielder", number: 11, nationality: "France" }, position: "CM", shirt_number: 11, rating: 7.5 },
      { player: { id: 408, name: "M. Musiala", slug: "jamal-musiala-408", position: "Midfielder", number: 42, nationality: "Germany" }, position: "CAM", shirt_number: 42, rating: 9.0 },
      { player: { id: 409, name: "L. Sané", slug: "leroy-sane-409", position: "Forward", number: 10, nationality: "Germany" }, position: "RW", shirt_number: 10, rating: 8.2 },
      { player: { id: 410, name: "M. Tel", slug: "mathys-tel-410", position: "Forward", number: 13, nationality: "France" }, position: "LW", shirt_number: 13, rating: 7.8 },
      { player: { id: 411, name: "H. Kane", slug: "harry-kane-411", position: "Forward", number: 9, nationality: "England" }, position: "ST", shirt_number: 9, rating: 9.2 },
    ],
    away_lineup: [
      { player: { id: 431, name: "G. Kobel", slug: "gregor-kobel-431", position: "Goalkeeper", number: 1, nationality: "Switzerland" }, position: "GK", shirt_number: 1, rating: 5.5 },
      { player: { id: 432, name: "R. Ryerson", slug: "ryerson-432", position: "Defender", number: 26, nationality: "Norway" }, position: "RB", shirt_number: 26, rating: 5.8 },
      { player: { id: 433, name: "M. Hummels", slug: "mats-hummels-433", position: "Defender", number: 15, nationality: "Germany" }, position: "CB", shirt_number: 15, rating: 5.5 },
      { player: { id: 434, name: "N. Schlotterbeck", slug: "niclas-schlotterbeck-434", position: "Defender", number: 4, nationality: "Germany" }, position: "CB", shirt_number: 4, rating: 5.6 },
      { player: { id: 435, name: "D. Malen", slug: "donyell-malen-435", position: "Defender", number: 22, nationality: "Netherlands" }, position: "LB", shirt_number: 22, rating: 5.7 },
      { player: { id: 436, name: "J. Brandt", slug: "julian-brandt-436", position: "Midfielder", number: 10, nationality: "Germany" }, position: "CM", shirt_number: 10, rating: 6.0 },
      { player: { id: 437, name: "E. Can", slug: "emre-can-437", position: "Midfielder", number: 23, nationality: "Germany" }, position: "CDM", shirt_number: 23, rating: 5.8 },
      { player: { id: 438, name: "M. Sabitzer", slug: "marcel-sabitzer-438", position: "Midfielder", number: 20, nationality: "Austria" }, position: "CM", shirt_number: 20, rating: 5.9 },
      { player: { id: 439, name: "J. Bynoe-Gittens", slug: "jamie-bynoe-gittens-439", position: "Forward", number: 43, nationality: "England" }, position: "RW", shirt_number: 43, rating: 6.2 },
      { player: { id: 440, name: "K. Adeyemi", slug: "karim-adeyemi-440", position: "Forward", number: 27, nationality: "Germany" }, position: "LW", shirt_number: 27, rating: 6.0 },
      { player: { id: 441, name: "S. Haller", slug: "sebastien-haller-441", position: "Forward", number: 9, nationality: "Ivory Coast" }, position: "ST", shirt_number: 9, rating: 5.8 },
    ],
    events: [
      { id: 30, minute: 11, added_time: null, type: "goal", team: BAYERN, player: { id: 411, name: "H. Kane", slug: "harry-kane-411", position: "Forward", number: 9, nationality: "England" }, second_player: { id: 408, name: "M. Musiala", slug: "jamal-musiala-408", position: "Midfielder", number: 42, nationality: "Germany" }, detail: "Penalty" },
      { id: 31, minute: 27, added_time: null, type: "goal", team: BAYERN, player: { id: 408, name: "M. Musiala", slug: "jamal-musiala-408", position: "Midfielder", number: 42, nationality: "Germany" }, second_player: { id: 409, name: "L. Sané", slug: "leroy-sane-409", position: "Forward", number: 10, nationality: "Germany" }, detail: "Dribble + finish" },
      { id: 32, minute: 38, added_time: null, type: "yellow_card", team: DORTMUND, player: { id: 437, name: "E. Can", slug: "emre-can-437", position: "Midfielder", number: 23, nationality: "Germany" }, second_player: null, detail: "Foul" },
      { id: 33, minute: 44, added_time: 1, type: "goal", team: BAYERN, player: { id: 411, name: "H. Kane", slug: "harry-kane-411", position: "Forward", number: 9, nationality: "England" }, second_player: null, detail: "Volley" },
      { id: 34, minute: 52, added_time: null, type: "goal", team: BAYERN, player: { id: 409, name: "L. Sané", slug: "leroy-sane-409", position: "Forward", number: 10, nationality: "Germany" }, second_player: { id: 411, name: "H. Kane", slug: "harry-kane-411", position: "Forward", number: 9, nationality: "England" }, detail: "Counter-attack" },
      { id: 35, minute: 60, added_time: null, type: "substitution", team: DORTMUND, player: { id: 442, name: "F. Nmecha", slug: "felix-nmecha-442", position: "Midfielder", number: 17, nationality: "Germany" }, second_player: { id: 437, name: "E. Can", slug: "emre-can-437", position: "Midfielder", number: 23, nationality: "Germany" }, detail: null },
      { id: 36, minute: 75, added_time: null, type: "substitution", team: BAYERN, player: { id: 443, name: "T. Müller", slug: "thomas-muller-443", position: "Forward", number: 25, nationality: "Germany" }, second_player: { id: 408, name: "M. Musiala", slug: "jamal-musiala-408", position: "Midfielder", number: 42, nationality: "Germany" }, detail: null },
      { id: 37, minute: 90, added_time: 1, type: "fulltime", team: BAYERN, player: { id: 401, name: "M. Neuer", slug: "manuel-neuer-401", position: "Goalkeeper", number: 1, nationality: "Germany" }, second_player: null, detail: null },
    ],
    stats: {
      possession: [62, 38],
      shots: [22, 8],
      shots_on_target: [12, 2],
      corners: [9, 3],
      fouls: [7, 11],
      yellow_cards: [0, 1],
      red_cards: [0, 0],
    },
  },

  // ── Inter Milan vs AC Milan (SCHEDULED) ──────────────────────────
  105: {
    id: 105,
    slug: "inter-vs-ac-milan-105",
    status: "scheduled",
    minute: null,
    date: "2026-08-22",
    kickoff_time: "20:45",
    venue: "San Siro",
    league: CHAMPIONS_LEAGUE,
    home_team: INTER,
    away_team: AC_MILAN,
    home_score: 0,
    away_score: 0,
    attendance: null,
    referee: "TBD",
    home_lineup: [],
    away_lineup: [],
    events: [],
    stats: {
      possession: [0, 0],
      shots: [0, 0],
      shots_on_target: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      yellow_cards: [0, 0],
      red_cards: [0, 0],
    },
  },

  // ── Juventus vs Napoli (SCHEDULED) ───────────────────────────────
  106: {
    id: 106,
    slug: "juventus-vs-napoli-106",
    status: "scheduled",
    minute: null,
    date: "2026-08-22",
    kickoff_time: "20:45",
    venue: "Allianz Stadium",
    league: CHAMPIONS_LEAGUE,
    home_team: JUVENTUS,
    away_team: NAPOLI,
    home_score: 0,
    away_score: 0,
    attendance: null,
    referee: "TBD",
    home_lineup: [],
    away_lineup: [],
    events: [],
    stats: {
      possession: [0, 0],
      shots: [0, 0],
      shots_on_target: [0, 0],
      corners: [0, 0],
      fouls: [0, 0],
      yellow_cards: [0, 0],
      red_cards: [0, 0],
    },
  },
};
